# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5c651605d888af3603cd076f88da34c3fcd391ae26c2dbc2370e7cd9b9e91e077680a6d9a429e0430665d942775e60bec32be792c0fdfd97d086377a662308c

test:
  secret_key_base: a46ae7d75ef04eb41f7616a899999f6776d2149516e7cb7d5c4292960b5e20400908130e1b49cb5bb350d166ca9a23f66174dd0216f7bbfec0832cfbea9da470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
